### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by bestxp** [domnikl/DomniklStatsdBundle#1]
After longtime daemon with lot of events we have
```
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 558653288 bytes) in .../vendor/domnikl/statsd/lib/Connection/InetSocket.php on line 126
```

**Comment by domnikl** [comment]
@bestxp This bundle is no longer being maintained and is only just a very thin wrapper around https://github.com/domnikl/statsd-php. Please open an issue there and describe what you did and how you use it. 

Looks like you are sending a lot of messages in bulk mode, thats more than 2GB of memory! You should split them up and send them separately to avoid allocating this much memory.
